# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestSpoty():
  def setUp(self):
      self.driver = webdriver.Firefox()
      self.vars = {}

  def test_spoty(self):
      self.driver.get("https://www.spotify.com/ar/signup/?forward_url=https%3A%2F%2Fwww.spotify.com%2Far%2Fdownload%2F")
      self.driver.maximize_window()
      self.driver.find_element(By.ID, "register-email").send_keys("Mervin.visma@gmail.com")
      self.driver.find_element(By.ID, "register-confirm-email").send_keys("mervin.visma@gmail.com")
      element = self.driver.find_element(By.ID, "register-email")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).click_and_hold().perform()
      element = self.driver.find_element(By.ID, "register-email")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      element = self.driver.find_element(By.ID, "register-email")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).release().perform()
      self.driver.find_element(By.ID, "register-email").click()
      self.driver.find_element(By.ID, "register-email").send_keys("mervin.visma@gmail.com")
      self.driver.find_element(By.ID, "register-password").click()
      self.driver.find_element(By.ID, "register-password").send_keys("Mm111213")
      self.driver.execute_script("window.scrollTo(0,408)")
      self.driver.find_element(By.ID, "register-displayname").send_keys("Mervin Diaz")
      self.driver.find_element(By.ID, "register-dob-day").click()
      self.driver.find_element(By.ID, "register-dob-day").send_keys("14")
      self.driver.find_element(By.ID, "register-dob-month").click()
      dropdown = self.driver.find_element(By.ID, "register-dob-month")
      dropdown.find_element(By.XPATH, "//option[. = 'enero']").click()
      self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
      self.driver.execute_script("window.scrollTo(0,408)")
      self.driver.find_element(By.ID, "register-dob-year").click()
      self.driver.find_element(By.ID, "register-dob-year").send_keys("1986")
      element = self.driver.find_element(By.ID, "register-male")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      self.driver.find_element(By.ID, "register-male").click()
      element = self.driver.find_element(By.CSS_SELECTOR, "body")
      actions = ActionChains(self.driver)
      actions.move_to_element(element, 0, 0).perform()
      element = self.driver.find_element(By.CSS_SELECTOR, ".l-signup-body > .container")
      actions = ActionChains( self.driver)
      actions.move_to_element(element).click_and_hold().perform()
      element = self.driver.find_element(By.CSS_SELECTOR, ".l-signup-body > .container")
      actions = ActionChains( self.driver)
      actions.move_to_element(element).perform()
      element = self.driver.find_element(By.CSS_SELECTOR, ".l-signup-body > .container")
      actions = ActionChains( self.driver)
      actions.move_to_element(element).release().perform()
      self.driver.find_element(By.ID, "register-thirdparty").click()
      self.driver.find_element(By.ID, "register-button-email-submit").click()
      self.driver.execute_script("window.scrollTo(0,431)")
      assert self.driver.find_element(By.CSS_SELECTOR, "#li-recaptcha > .has-error:nth-child(5)").text == "Confirma que no eres un robot."
  

  def teardown_method(self, method):
    self.driver.quit()